{{- if .Values.objects.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/ingress.allow-http: "true"
    {{- if .Values.ingress.annotations.rewrite_target.enabled }}
    nginx.ingress.kubernetes.io/rewrite-target: {{ .Values.ingress.annotations.rewrite_target.value }}
    {{- end }}
    {{- if .Values.ingress.annotations.app_root.enabled }}
    nginx.ingress.kubernetes.io/app-root: {{ .Values.ingress.annotations.app_root.value }}
    {{- end }}
spec:
  rules:
  {{- range .Values.ingress.rules }}
  - host: {{ .host }}.{{ .domain }}
    http:
      paths:
      - path: {{ .path }}
        pathType: Prefix
        backend:
          service:
            name: {{ $.Release.Name }}
            port:
              number: {{ $.Values.port }}
  {{- end }}
  {{- if .Values.ingress.tlsenabled }}
  tls:
  {{- range .Values.ingress.tls }}  
  - hosts:
    - {{ .host }}.{{ .domain }}
    secretName: {{ .secretname }}
  {{- end }}
  {{- end }}
{{- end }}