{{- if .Values.objects.secret.enabled }}
apiVersion: v1
data:
  GF_DATABASE_USER: {{ .Values.env.GF_DATABASE_USER }}
  GF_DATABASE_PASSWORD: {{ .Values.env.GF_DATABASE_PASSWORD }}
kind: Secret
metadata:
  name: {{ $.Release.Name }}
{{- end }}